# fly.toml app configuration file generated for foodlens on 2025-05-13T10:42:56+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'foodlens'
primary_region = 'sin'

[build]

# This tells Fly.io to use the default build process (which uses Docker)
# Fly.io will automatically detect your Dockerfile

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
